[project]
name = "metamorphio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.45",
]
